# basic options
title: Michael McMahon
author:
  name: Michael McMahon
  email: michael_mc_mahon@outlook.ie
  github_username:  mike-mc-mahon
  twitter_username: Mc_econ
description: "test content."

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

theme: jekyll-theme-slate